version: "3.9"

services:
  db:
    image: postgres:15.7-alpine
    environment:
      POSTGRES_DB: provedcode
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: backend
    image: rpid01/provedcode-backend 
    depends_on:
      - db
      - localstack
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: db/provedcode
      DB_LOGIN: app_user
      DB_PASSWORD: app_pass
      S3_REGION: us-east-2
      BUCKET: my-bucket
      S3_ACCESS_KEY: test
      AWS_SECRET_ACCESS_KEY: test
    healthcheck:
      test: wget -qO- --tries=1 http://localhost:8080/actuator/health | grep UP || exit 1
      interval: 3s
      timeout: 5s
      retries: 10

  frontend:
    container_name: frontend
    image: rpid01/provedcode-frontend 
    ports:
      - "80:80"
    depends_on:
      backend: 
        condition: service_healthy
    environment:
       REACT_APP_BASE_URL: ''

  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - AWS_DEFAULT_REGION=us-east-2
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgres_data: {}