version: "3.9"

services:
  # PostgreSQL database
  db:
    image: postgres:15.7
    environment:
      POSTGRES_DB: provedcode  # Replace with your desired database name
      POSTGRES_USER: app_user  # Replace with your desired username
      POSTGRES_PASSWORD: app_pass  # Replace with your desired password
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent storage for database data
    network_mode: bridge

  # Java backend
  backend:
    build: ./  # Path to your backend Dockerfile
    ports:
      - "8080:8080"  # Map container port 8080 to host port 8080
    depends_on:
      - db  # Backend depends on the database to be ready
    environment:
      # Add any environment variables your backend application needs
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: 172.17.0.4/provedcode
      DB_LOGIN: app_user  # Same username used in the db service
      DB_PASSWORD: app_pass  # Same password used in the db service
      S3_REGION: us-east-1 
      BUCKET: my-bucket
      S3_ACCESS_KEY: test
      AWS_SECRET_ACCESS_KEY: test
    network_mode: bridge

  frontend:
    build: ../provedcode-frontend-rpid/  # Path to your frontend Dockerfile
    ports:
      - "3000:80"  # Map container port 3000 (default for Next.js) to host port 3000
    depends_on:
      - backend  # Frontend depends on the backend to be ready
    environment:
      # Add any environment variables your frontend application needs
      REACT_APP_BASE_URL: http://localhost:8080
    network_mode: bridge 

# Define a volume for persistent database storage
volumes:
  postgres_data: {}
