version: "3.9"

services:
  # PostgreSQL database
  db:
    image: postgres:15.7
    environment:
      POSTGRES_DB: provedcode  # Replace with your desired database name
      POSTGRES_USER: app_user  # Replace with your desired username
      POSTGRES_PASSWORD: app_pass  # Replace with your desired password
    depends_on:
      - localstack
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent storage for database data
  #  network_mode: bridge

  # Java backend
  backend:
    build: ./  # Path to your backend Dockerfile
    #ports:
    #  - "8080:8080"  # Map container port 8080 to host port 8080
    depends_on:
      - db  # Backend depends on the database to be ready
    environment:
      # Add any environment variables your backend application needs
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: db/provedcode
      DB_LOGIN: app_user  # Same username used in the db service
      DB_PASSWORD: app_pass  # Same password used in the db service
      S3_REGION: us-east-2
      BUCKET: my-bucket
      S3_ACCESS_KEY: test
      AWS_SECRET_ACCESS_KEY: test
  #  network_mode: bridge
    healthcheck:
      test: wget --no-verbose -O /dev/null --tries=1 http://localhost:8080/actuator/health | grep UP || exit 1
      interval: 1s
      timeout: 3s
      retries: 10

  frontend:
    container_name: frontend
    build: ../provedcode-frontend-rpid/  # Path to your frontend Dockerfile
    ports:
      - "80:80"  # Map container port 3000 (default for Next.js) to host port 3000
    depends_on:
      backend:  # Frontend depends on the backend to be ready
        condition: service_started
    environment:
      # Add any environment variables your frontend application needs
       REACT_APP_BASE_URL: http://localhost
  #  network_mode: bridge 

  localstack:
    container_name: localstack
    image: localstack/localstack
  #  network_mode: bridge
    ports:
      - "4566:4566"
    environment:
      - AWS_DEFAULT_REGION=us-east-2
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
      - /var/run/docker.sock:/var/run/docker.sock

# Define a volume for persistent database storage
volumes:
  postgres_data: {}

networks:
  default:
    external: true
    name: toto_network