apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: AWS_SECRET_ACCESS_KEY
              value: test
            - name: BUCKET
              value: my-bucket
            - name: DB_LOGIN
              value: app_user
            - name: DB_PASSWORD
              value: app_pass
            - name: DB_URL
              value: db/provedcode
            - name: S3_ACCESS_KEY
              value: test
            - name: S3_REGION
              value: us-east-2
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          image: rpid01/provedcode-backend
          livenessProbe:
            exec:
              command:
                - wget -qO- http://localhost:8080/actuator/health | grep UP || exit 1
            failureThreshold: 10
            periodSeconds: 3
            timeoutSeconds: 5
          name: backend
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always