on:
  pull_request:
  push: 
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
  actions: read
  checks: write 
jobs:
  build-test:
    name: Build & Test Java Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out your repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
        
      - name: Build and Run Tests
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
          
  push_to_registry:
    name: Build & Push Docker Image 
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push to registry
        uses: docker/build-push-action@v6
        env:
          SPRING_PROFILES_ACTIVE: dev
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/provedcode-backend:dev
