name: Java CI & CD

on:
  pull_request:
  push: 
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
  actions: read
  checks: write
  id-token: write
jobs:
  build-test:
    name: Build & Test Java Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out your repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
        
      - name: Build and Run Tests
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
          
  push_to_registry:
    name: Build & Push Docker Image 
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Make executeable
        run: chmod +x ./mvnw
        
      - name: Build and push to registry
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/provedcode-backend:${{ github.run_id }}
          
  deploy_on_cluster:
    name: Deploy Backend on EKS cluster
    runs-on: ubuntu-latest
    needs: push_to_registry
    steps:
      - name: Check out the repo 
        uses: actions/checkout@v3  

      - name: Install Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.30.3' 
        id: install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Update KubeConfig
        run:  aws eks update-kubeconfig --region ${{ vars.AWS_REGION }} --name ${{ vars.CLUSTER_NAME }}

      - name: Update deployment image
        run: |
              kubectl set env deployment/backend S3_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY_ID }} S3_SECRET_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} S3_REGION=${{ vars.AWS_REGION }} BUCKET=${{ vars.S3_BUCKET }}   
              kubectl set image deployment/backend backend=${{secrets.DOCKERHUB_USERNAME}}/provedcode-backend:${{ github.run_id }}
              kubectl rollout status deployment/backend
