name: Build java backend
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  checking-pipeline:
    runs-on: ubuntu-latest

    steps:

      - name: Checks-out your repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
        
      - name: Build and Run Tests
        run: mvn clean verify
        
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
