name: Deployment On K8s Cluster

on: 
  workflow_run:
    workflows: [Java CI & Build Docker Image]
    branches: [localstack]
    types:
      - completed 
permissions:
  id-token: write
  contents: read     

jobs:
  Deploy_On_Cluster:
    name: Deploy Application On Cluster
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo 
        uses: actions/checkout@v3  

      - name: Install Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.29' 
        id: install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update KubeConfig
        run: | 
              mkdir -p $HOME/.kube
              echo "$KUBE_CONFIG_DATA" | base64 -d > $HOME/.kube/config
              aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.CLUSTER_NAME }}

      - name: Show cluster status
        run: kubectl get all
